### ISSUE TITLE
Markdown Code Block Style

### ISSUE THREAD

**Issue by jaybkim1** [Huxpro/huxpro.github.io#256]
## Using Backtick (```}

![screen shot 2018-09-19 at 5 55 31 pm](https://user-images.githubusercontent.com/20435620/45742561-3a2b3980-bc35-11e8-8d7e-588beb313cf8.png)

## Expected Code Block Style (line numbers, dark theme)

![screen shot 2018-09-19 at 5 54 35 pm](https://user-images.githubusercontent.com/20435620/45742506-1962e400-bc35-11e8-8e94-ede4f9e67ebc.png)

![hexo-highlight-ex](https://user-images.githubusercontent.com/20435620/45743554-3ef0ed00-bc37-11e8-8495-f9384fcda8c4.png)

**Do I need to customize this theme using some type of plugin to achieve the expected code block style?**

Here is what I configured in global `_config.yml`

```
highlight:
  enable: true
  line_number: true
  auto_detect: false # TypeError: Cannot set property 'lastIndex' of undefined
  tab_replace:
```

Thank you for this fascinating theme!
