### ISSUE TITLE
表格上边框不显示

### ISSUE THREAD

**Issue by ZingLix** [Huxpro/huxpro.github.io#259]
跟进1.8之后，发现此问题，表格的上边框消失。

![image](https://user-images.githubusercontent.com/22333469/46049992-26fff880-c164-11e8-8705-7b0b836b5af0.png)

因为貌似作者博客中没有用到表格，所以我尝试直接clone这个repo然后在post里面插入表格仍有问题。

**Comment by Huxpro** [comment]
https://huangxuan.me/2017/01/09/wechat-miniapp-ux/

你访问这里看看表格 ok 吗？

**Comment by ZingLix** [comment]
> https://huangxuan.me/2017/01/09/wechat-miniapp-ux/
> 
> 你访问这里看看表格 ok 吗？

也看不到上边框。。我试了 chrome 和 edge 都不行

![image](https://user-images.githubusercontent.com/22333469/46072416-e67c9b00-c1b4-11e8-90af-5fa166d6ff51.png)

不过够窄的时候正常

![image](https://user-images.githubusercontent.com/22333469/46072601-5ab73e80-c1b5-11e8-82df-29c6ba1d2a3d.png)

**Comment by ZingLix** [comment]
我大概研究了下，好像是8476799这次提交，因为新的 Code Theme 里调整了 table 的边框，导致普通表格的边框出现了问题，我在css里加了个.table的border属性，.highlight .table 里把border设成 0，问题解决

不过我没学过前端，不知道这样操作是否规范。。

**Comment by Huxpro** [comment]
@ZingLix Interesting. I do confirm this bug existed in my windows laptop but not in my MacBook. Will investigate it later. (Sorry I was in an English-input-method only device)

**Comment by PotatoDrug** [comment]
I found the problem to be in bootstrap, the following code in bootstrap causes the border to be removed.
```css
.table > caption + thead > tr:first-child > th,
.table > colgroup + thead > tr:first-child > th,
.table > thead:first-child > tr:first-child > th,
.table > caption + thead > tr:first-child > td,
.table > colgroup + thead > tr:first-child > td,
.table > thead:first-child > tr:first-child > td {
  border-top: 0;
}
```
I fixed it by overwriting the bootstrap code in the custom css.
```css
.table > caption + thead > tr:first-child > th,
.table > colgroup + thead > tr:first-child > th,
.table > thead:first-child > tr:first-child > th,
.table > caption + thead > tr:first-child > td,
.table > colgroup + thead > tr:first-child > td,
.table > thead:first-child > tr:first-child > td {
  border-top: 1px solid #eee;
}
```
