### ISSUE TITLE
请问如何设计博客某篇文章置顶？

### ISSUE THREAD

**Issue by Accelerator086** [Huxpro/huxpro.github.io#353]
- [ ] 置顶文章
求问如何在首页的文章post list里置顶其中一篇文章呢？

**Comment by DotIN13** [comment]
修改/index.html，将原有的
```html
{% for post in site.posts %}
...
{% endfor %}
```
修改为如下：
```html
{% for post in site.posts %}
{% if post.onTop == true %}
<div class="post-preview">
    <a href="{{ post.url | prepend: site.baseurl }}">
    <div class="ontop-title-group">
        <span class="ontop-pushpin glyphicon glyphicon-pushpin"></span>
        <h2 class="ontop post-title" style="display: inline;">
            {{ post.title }}
        </h2>
    </div>
        {% if post.subtitle %}
        <h3 class="post-subtitle">
            {{ post.subtitle }}
        </h3>
        {% endif %}
        <div class="post-content-preview">
            {% if post.lang == 'en' %}
            {{ post.content | strip_html | truncate:300 }}
            {% else %}
            {{ post.content | strip_html | truncate:200 }}
            {% endif %}
        </div>
    </a>
    <p class="post-meta">
        Posted by {% if post.author %}{{ post.author }}{% else %}{{ site.title }}{% endif %} on
        {{ post.date | date: "%B %-d, %Y" }}
    </p>
</div>
<hr>
{% endif %}
{% endfor %}

{% for post in paginator.posts %}
{% if post.onTop != true %}
<div class="post-preview">
    <a href="{{ post.url | prepend: site.baseurl }}">
        <h2 class="post-title">
            {{ post.title }}
        </h2>
        {% if post.subtitle %}
        <h3 class="post-subtitle">
            {{ post.subtitle }}
        </h3>
        {% endif %}
        <div class="post-content-preview">
            {% if post.lang == 'en' %}
            {{ post.content | strip_html | truncate:300 }}
            {% else %}
            {{ post.content | strip_html | truncate:200 }}
            {% endif %}
        </div>
    </a>
    <p class="post-meta">
        Posted by {% if post.author %}{{ post.author }}{% else %}{{ site.title }}{% endif %} on
        {{ post.date | date: "%B %-d, %Y" }}
    </p>
</div>
<hr>
{% endif %}
{% endfor %}
```
原理即先遍历所有文章，判断post文件的YAML中是否包含`onTop: true`，包含则显示在最上方，然后再遍历一次所有文章，将`onTop != true`的文章依照paginator的分页显示在页面中。

然后在你要置顶的文章的YAML中添加onTop: true即可。

`<span class="ontop-pushpin glyphicon glyphicon-pushpin"></span>`是一个图钉标志，我的css如下，可以添加到hux-blog.css中，记得minify，当然不喜欢也可以删除这个图钉：
```css
/*post on top*/
.ontop-pushpin {
  display: inline;
  box-sizing: border-box;
  border: 1px solid grey;
  padding: .2rem .75rem .15rem .75rem;
  margin-right: .5rem;
  border-radius: .25em;
  top: -2px;
  font-size: 14px;
}

.ontop-title-group {
  display: block;
  margin-top: 20px;
  margin-bottom: 10px;
}

@media only screen and (min-width: 768px) {
  .ontop-pushpin {
    padding: 0.275rem 0.75rem 0.175rem 0.75rem;
    top: -3px;
  }
}
```
