### ISSUE TITLE
修改字体

### ISSUE THREAD

**Issue by ZainChenDev** [Huxpro/huxpro.github.io#401]
请问应该在哪里修改字体呢。具体到某个元素的字体，可以用浏览器开发者模式检索到div的id，这时候应该去哪儿修改对应的字体呢？

**Comment by DotIN13** [comment]
添加CSS代码到`css/hux-blog.css`。

例如

```css
#id { // 元素的选择器
  font-family: "Microsoft Yahei", sans-serif; // 配置字体
}
```
