### ISSUE TITLE
错误：当前运行程序（ubuntu-24.04-x64）被检测为自托管，因为该平台与GitHub托管的运行程序映像不匹配（或者该映像已弃用且不再受支持）。

### ISSUE THREAD

**Issue by Putao-1** [Huxpro/huxpro.github.io#502]
Error: The current runner (ubuntu-24.04-x64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
In such a case, you should install Ruby in the $RUNNER_TOOL_CACHE yourself, for example using https://github.com/rbenv/ruby-build
You can take inspiration from this workflow for more details: https://github.com/ruby/ruby-builder/blob/master/.github/workflows/build.yml
$ ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
Once that completes successfully, mark it as complete with:
$ touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete
It is your responsibility to ensure installing Ruby like that is not done in parallel.

**Comment by Rainbow-prince** [comment]
是不是jekyll.yml的问题，里面把ubuntu的版本改成22.04就可以了

**Comment by pinylin** [comment]
替换掉这一项吧
```yaml
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
```
