### ISSUE TITLE
文章左右对齐

### ISSUE THREAD

**Issue by TerminusBot** [Huxpro/huxpro.github.io#95]
文章右边没有对齐，呈锯齿状比较难看。不知道有什么办法可以解决。查了下可以用`text-align:justify;`，但是不知道怎么改。

**Comment by LAIHAOTAO** [comment]
1. 这里提供一个解决方案，在根目录的css文件夹当中找到hux-blog.css文件
2. 添加以下代码并保存，原因是所有的文章都会在class为`post-container`的div当中
```css
.post-container {
  text-align: justify;
}
```
3. 将这个css重新生成min.css并覆盖同一个目录下的hux-blog.min.css文件

ps：生成min.css可以到[这里](http://www1.w3cfuns.com/tools.php?mod=compression)，注意要选择css不要js

以上。
